from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = env('DEBUG')
DEBUG = True

ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS').split(',')

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

CURRENT_SITE = env('CURRENT_SITE')

# BulkSMS otp settings
BULK_SMS_OTP_URL = env('BULK_SMS_OTP_URL')
BULK_SMS_API_TOKEN = env('BULK_SMS_API_TOKEN')

# Termii otp settings
# TERMII_OTP_TOKEN = "TLxSKtbXUGXFGZmYCBFodMPWeTwYSdsDwrqHhKZvRqWYgIJXzGsSFsRRoibgXA"
TERMII_OTP_TOKEN = "TTdkSJGmfTnHHNLedsfPdBaRQZbWeQWxZPsQkojHFgkiGNuHyZBcZXiigYrZVA"
TERMII_OTP_URL = "https://v3.api.termii.com/api/sms/send"


# [EMAIL]
MAIL_PORT=env('MAIL_PORT')
EMAIL_USE_TLS=env('EMAIL_USE_TLS')
MAIL_SERVER=env('MAIL_SERVER')
MAIL_USER=env('MAIL_USER')
MAIL_PASS=env('MAIL_PASS')

CORALPAY_INVOKEPAYMENT_URL = env('CORALPAY_INVOKEPAYMENT_URL')
CORALPAY_TRANSACTIONQUERY_URL = env('CORALPAY_TRANSACTIONQUERY_URL')
CORALPAY_INVOKE_USSD_URL = env('CORALPAY_INVOKE_USSD_URL')

# CORALPAY_RETURN_URL = "https://google.com"
CORALPAY_RETURN_URL = env('CORALPAY_RETURN_URL')
CORALPAY_CALLBACKURL_SUCCESS = env('CORALPAY_CALLBACKURL_SUCCESS')
CORALPAY_WEBSOCKETURL_SUCCESS = env('CORALPAY_WEBSOCKETURL_SUCCESS')
CORALPAY_CALLBACKURL_FAILURE = env('CORALPAY_CALLBACKURL_FAILURE')
CORALPAY_WEBSOCKETURL_FAILURE = env('CORALPAY_WEBSOCKETURL_FAILURE')
CORALPAY_TRACEID = env('CORALPAY_TRACEID')
CORALPAY_TERMINALID = env('CORALPAY_TERMINALID')
CORALPAY_PRODUCTID = env('CORALPAY_PRODUCTID')
CORALPAY_MERCHANT_USERNAME = env('CORALPAY_MERCHANT_USERNAME')
CORALPAY_MERCHANT_PASSWORD = env('CORALPAY_MERCHANT_PASSWORD')
CORALPAY_MERCHANTID = env('CORALPAY_MERCHANTID')
CORALPAY_KEY = env('CORALPAY_KEY')
CORALPAY_TOKEN = env('CORALPAY_TOKEN')

# PAY WITH CARD DETAILS
CORALPAY_REQUESTPAYMENTWITHCARD_URL = env('CORALPAY_REQUESTPAYMENTWITHCARD_URL')
CORALPAY_CARD_MERCHANTID = env('CORALPAY_CARD_MERCHANTID')
CORALPAY_PAYWITHCARD_TOKEN = env('CORALPAY_PAYWITHCARD_TOKEN')

# PAY WITH DYNAMIC BANK TRANSFER
CORALPAY_CLIENTID = env('CORALPAY_CLIENTID')
CORALPAY_DYNAMIC_PAYWITHTRANSFER_URL = env('CORALPAY_DYNAMIC_PAYWITHTRANSFER_URL')
CORALPAY_DPWT_USERNAME = env('CORALPAY_DPWT_USERNAME')

# PAY WITH STATIC BANK TRANSFER
CORALPAY_STATIC_PAYWITHTRANSFER_URL = env('CORALPAY_STATIC_PAYWITHTRANSFER_URL')

# PAY WITH TRANSFER REQUERY
CORALPAY_PAYWITHTRANSFER_REQUERY_URL = env('CORALPAY_PAYWITHTRANSFER_REQUERY_URL')
CORALPAY_CLIENT_PASSWORD = env('CORALPAY_CLIENT_PASSWORD')

# FETCH ACCOUNT TRANSACTIONS
CORALPAY_FETCH_ACCOUNT_TRANSACTIONS_URL = env('CORALPAY_FETCH_ACCOUNT_TRANSACTIONS_URL')

# FETCH PARTNER TRANSACTIONS
CORALPAY_FETCH_PARTNER_TRANSACTIONS_URL = env('CORALPAY_FETCH_PARTNER_TRANSACTIONS_URL')

# TRANSACTION PAYMENT NOTIFICATION
CORALPAY_MERCHANT_ACCOUNT_NUMBER = env('CORALPAY_MERCHANT_ACCOUNT_NUMBER')
CORALPAY_MERCHANT_PAYMENT_NOTIFICATION_URL = env('CORALPAY_MERCHANT_PAYMENT_NOTIFICATION_URL')

# GET BANK LIST 
CORALPAY_GET_BANK_LIST_URL = env('CORALPAY_GET_BANK_LIST_URL')

# PAY DIRECT URL
CORALPAY_PAYDIRECT_URL = env('CORALPAY_PAYDIRECT_URL')


# CORALPAY USSD API 
CORALPAY_USSD_AUTHENTICATION_URL = env('CORALPAY_USSD_AUTHENTICATION_URL')
CORALPAY_USSD_USERNAME = env('CORALPAY_USSD_USERNAME')
CORALPAY_USSD_PASSWORD = env('CORALPAY_USSD_PASSWORD')
CORALPAY_INVOKEREFERENCE_URL = env('CORALPAY_INVOKEREFERENCE_URL')
CORALPAY_INVOKEREFERENCE_TOKEN = env('CORALPAY_INVOKEREFERENCE_TOKEN')
CORALPAY_INVOKEREFERENCE_MERCHANTID = env('CORALPAY_INVOKEREFERENCE_MERCHANTID')
CORALPAY_INVOKEREFERENCE_TERMINALID = env('CORALPAY_INVOKEREFERENCE_TERMINALID')
CORALPAY_INVOKEREFERENCE_KEY = env('CORALPAY_INVOKEREFERENCE_KEY')
CORALPAY_USSD_REFUND_URL = env('CORALPAY_USSD_REFUND_URL')
CORALPAY_TRANSACTIONSTATUS_URL = env('CORALPAY_TRANSACTIONSTATUS_URL')
CORALPAY_GETBANKLIST_URL = env('CORALPAY_GETBANKLIST_URL')
